---
baseURL: https://j4y3eee.github.io/
languageCode: en-us
title: Jayeee's Note
pygmentsstyle: monokai
metaDataFormat: yaml
module:
  imports:
  - path: github.com/forestryio/hugo-theme-novela
paginate: "6"
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
